version: "3"

networks:
    innerFastAPI:

services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            database:
                condition: service_healthy
        networks:
            - innerFastAPI
    database:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $DB_PASS
            MYSQL_DATABASE: $DB_SCHEMA
            TZ: Europe/Paris
        ports:
            - "9906:3306"
        networks:
            - innerFastAPI
        volumes:
            - ./deploy/prod/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 3
