version: "3"

networks:
    innerFastAPI:
        external: true

services:
    fastapi_todo-awsgi:
        image: 057133510824.dkr.ecr.eu-west-3.amazonaws.com/fastapi_todo:latest
        ports:
            - "8080:8080"
        depends_on:
            database:
                condition: service_healthy
        networks:
            - innerFastAPI
    database:
        container_name: fastapi_todo-db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $DB_PASS
            MYSQL_DATABASE: $DB_SCHEMA
            TZ: Europe/Paris
        ports:
            - "9906:3306"
        networks:
            - innerFastAPI
        volumes:
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 10s
            retries: 3
